# Here all dependencies written & installed which are needed
# This is a basic workflow to help you get started with Actions
# Finally, the workflow file run-tests.yml should contain the following text. 
# Note that we specify on: push so the workflow is executed whenever something is pushed.

name: Run Tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H http://64.226.92.208:8000 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no user@http://64.226.92.208:8000 'your-deployment-command'
        
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.0'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
