# Here all dependencies written & installed which are needed
# This is a basic workflow to help you get started with Actions
# Finally, the workflow file run-tests.yml should contain the following text. 
# Note that we specify on: push so the workflow is executed whenever something is pushed.

name: Run Tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.0'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
      
  deploy:
    runs-on: ubuntu-20.04
    needs: run-tests
    steps:
    
    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          ls
          cd /home/assignment_cd
          pwd
          ls
          git pull origin main
          systemctl restart assignment_cd
          systemctl status assignment_cd
          
        
  
